-- TASK 1
BEGIN;

CREATE TABLE CLIENTS
(
    ID serial,
    NAME varchar(1000),
    PLACE_OF_BIRTH varchar(1000),
	DATE_OF_BIRTH date,
	ADDRESS varchar(1000),
	PASSPORT varchar(100),
	
	CONSTRAINT CLIENTS_PK PRIMARY Key (ID)
);

CREATE TABLE TARIFS
(
    ID serial,
    NAME varchar(100),
	COST numeric,
	
	CONSTRAINT TARIFS_PK PRIMARY Key (ID)
);

CREATE TABLE PRODUCT_TYPE
(
    ID serial,
    NAME varchar(100),
	BEGIN_DATE date,
	END_DATE date,
	TARIF_REF int,
	
	CONSTRAINT PRODUCT_TYPE_PK PRIMARY Key (ID),
	CONSTRAINT PROD_TYPE_TAR_FK
		FOREIGN KEY(TARIF_REF)
			REFERENCES TARIFS(ID)
);

CREATE TABLE PRODUCTS
(
    ID serial,
    PRODUCT_TYPE_ID int,
    NAME varchar(100),
	CLIENT_REF int,
	OPEN_DATE date,
	CLOSE_DATE date,
	
	CONSTRAINT PRODUCTS_PK PRIMARY Key (ID),
	CONSTRAINT PROD_CL_FK
		FOREIGN KEY(CLIENT_REF)
			REFERENCES CLIENTS(ID),
	CONSTRAINT PROD_PRODTYPE_FK
		FOREIGN KEY(PRODUCT_TYPE_ID)
			REFERENCES PRODUCTS(ID)
);

CREATE TABLE ACCOUNTS
(
    ID serial,
    NAME varchar(100),
    SALDO numeric,
	CLIENT_REF int,
	OPEN_DATE date,
	CLOSE_DATE date,
	PRODUCT_REF int,
	ACC_NUM varchar(25),
	
	CONSTRAINT ACCOUNTS_PK PRIMARY Key (ID),
	CONSTRAINT ACC_CL_FK
		FOREIGN KEY(CLIENT_REF)
			REFERENCES CLIENTS(ID),
	CONSTRAINT ACC_PROD_FK
		FOREIGN KEY(PRODUCT_REF)
			REFERENCES PRODUCTS(ID)
);

CREATE TABLE RECORDS(
	ID serial,
	DT bool,
	SUM numeric,
	ACC_REF int,
	OPER_DATE date,
	
	CONSTRAINT RECORDS_PK PRIMARY Key (ID),
	CONSTRAINT REC_ACC_FK
		FOREIGN KEY(ACC_REF)
			REFERENCES ACCOUNTS(ID)
);

COMMIT;